import { notFound } from "next/navigation";
import { projectsService } from "@/application/projects.service";
import { boardService } from "@/application/board.service";
import { getDict } from "@/i18n/server";
import { PublicBoardView } from "@/features/board/PublicBoardView";

/**
 * Public read-only board view via token — no login required.
 * For demos/project showcases; the link is generated by the project owner.
 */
export default async function PublicBoardPage({
  params,
}: {
  params: Promise<{ token: string }>;
}) {
  const { token } = await params;
  if (!/^[0-9a-f-]{16,36}$/i.test(token)) notFound();

  const project = await projectsService.findByPublicToken(token);
  if (!project) notFound();

  const [columns, dict] = await Promise.all([
    boardService.getBoard(project.id),
    getDict(),
  ]);

  return (
    <PublicBoardView
      title={project.name}
      subtitle={dict.board.publicBoardSubtitle}
      columns={columns}
      dict={dict}
    />
  );
}
